### ISSUE TITLE
codecommit is deprecated, need to update solution to use github or other providers

### ISSUE THREAD

**Issue by connect2kish** [aws-samples/lza-account-creation-workflow#14]
**Is your feature request related to a problem? Please describe.**
LZA deployment had failed due to the creation of the code commit repository, which has since been deprecated and no longer available for new accounts since July 25, 2024

**Describe the feature you'd like** 
Update the solution to use github or other providers as the code repo for LZA config files.

**Additional context**

**Comment by JustinKuskowski** [comment]
Fixed in version v1.2.0
